### ISSUE TITLE
Compile execution error

### ISSUE THREAD

**Issue by lnx252008** [hilanmiao/LanMiaoDesktop#2]
1   npm install
2   npm run build

          | ./node_modules/vue-style-loader/lib/addStylesClient.js 6.09 KiB [built]
          | ./node_modules/vue-style-loader/lib/listToStyles.js 637 bytes [built]
     [52] ./node_modules/element-ui/lib/theme-chalk/base.css 435 bytes {0} [built]
     [70] ./node_modules/element-ui/lib/upload.js 35.1 KiB {0} [built]
     [71] ./node_modules/element-ui/lib/button.js 10 KiB {0} [built]
     [72] external "axios" 42 bytes {0} [built]
     [78] ./node_modules/vuetify/dist/vuetify.js 1.05 MiB {0} [built]
     [79] ./node_modules/element-ui/lib/theme-chalk/upload.css 437 bytes {0} [built]
     [93] ./node_modules/element-ui/lib/theme-chalk/button.css 437 bytes {0} [built]
     [95] ./node_modules/@vue/devtools/index.js 639 bytes {0} [built]
    [172] ./node_modules/vuetify/dist/vuetify.min.css 436 bytes {0} [built]
    [174] ./node_modules/material-design-icons-iconfont/dist/material-design-icons.css 446 bytes {0} [built]
    [180] external "vue-electron" 42 bytes {0} [built]
    [182] ./src/renderer/main.js + 8 modules 5.53 KiB {0} [built]
          | ./src/renderer/main.js 923 bytes [built]
          | ./src/renderer/App.vue 511 bytes [built]
          | ./src/renderer/router/index.js 2.56 KiB [built]
          | ./src/renderer/store/index.js 397 bytes [built]
          | ./src/renderer/App.vue?vue&type=template&id=7b5edda6& 201 bytes [built]
          | ./src/renderer/App.vue?vue&type=script&lang=js& 344 bytes [built]
          | ./src/renderer/store/plugins/todo.js 322 bytes [built]
          | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/App.vue?vue&type=template&id=7b5edda6& 210 bytes [built]
          | ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/App.vue?vue&type=script&lang=js& 37 bytes [built]
        + 175 hidden modules

    **ERROR in Template execution failed: ReferenceError: process is not defined**

    ERROR in   ReferenceError: process is not defined

      - index.ejs:771
        D:/Electron/LanMiaoDesktop/src/index.ejs:771:2

      - index.ejs:776 module.exports
        D:/Electron/LanMiaoDesktop/src/index.ejs:776:3

      - index.js:284
        [LanMiaoDesktop]/[html-webpack-plugin]/index.js:284:18

    Child html-webpack-plugin for "index.html":
             Asset     Size  Chunks  Chunk Names
        index.html  556 KiB       0
        Entrypoint undefined = index.html
        [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 1.2 KiB {0} [built]
        [1] ./node_modules/lodash/lodash.js 527 KiB {0} [built]
        [2] (webpack)/buildin/module.js 497 bytes {0} [built]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! PocketBook@0.0.2 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PocketBook@0.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Apple\AppData\Roaming\npm-cache\_logs\2019-06-18T14_01_16_153Z-debug.log

**Comment by hilanmiao** [comment]
Sorry, I recently found this problem on the mac.The current version only runs on windows, I will modify and test it later to run on mac.
you can change webpack setting like this.

**webpack.render.config**

```
new HtmlWebpackPlugin({
      filename: 'index.html',
      template: path.resolve(__dirname, '../src/index.ejs'),
      templateParameters(compilation, assets, options) {
        return {
          compilation: compilation,
          webpack: compilation.getStats().toJson(),
          webpackConfig: compilation.options,
          htmlWebpackPlugin: {
            files: assets,
            options: options
          },
          process,
        };
      },
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true
      },
      nodeModules: process.env.NODE_ENV !== 'production'
        ? path.resolve(__dirname, '../node_modules')
        : false
    }),
```

**webpack.web.config**

```
new HtmlWebpackPlugin({
            filename: 'index.html',
            template: path.resolve(__dirname, '../src/index.ejs'),
            templateParameters(compilation, assets, options) {
                return {
                    compilation: compilation,
                    webpack: compilation.getStats().toJson(),
                    webpackConfig: compilation.options,
                    htmlWebpackPlugin: {
                        files: assets,
                        options: options
                    },
                    process,
                };
            },
            minify: {
                collapseWhitespace: true,
                removeAttributeQuotes: true,
                removeComments: true
            },
            nodeModules: false
        }),
```

**Comment by lnx252008** [comment]
The current version only runs on windows.
However, my running environment is Windows, which also causes such problems.

**Comment by hilanmiao** [comment]
Please download the latest code and run it. If there is still a problem, maybe you can send the source code to me.
