### ISSUE TITLE
linux打包

### ISSUE THREAD

**Issue by cqdjsp** [hilanmiao/LanMiaoDesktop#21]
看到您打包了linux，我试了一下，也可以在linux上运行，虽然有点显示上的问题。不知您是如何进行linux程序打包的呢？

**Comment by hilanmiao** [comment]
> 看到您打包了linux，我试了一下，也可以在linux上运行，虽然有点显示上的问题。不知您是如何进行linux程序打包的呢？

我用得是travis-ci开源持续集成服务，支持linux、macos镜像，多种语言、构建工具打包项目。如果你想自己打包，需要有一台linux机器，如安装ubuntu操作系统得电脑。
