### ISSUE TITLE
为什么启动之后是项目目录

### ISSUE THREAD

**Issue by Mrchen128** [hilanmiao/LanMiaoDesktop#27]
为什么启动之后是项目目录

**Comment by Mrchen128** [comment]
1. yarn install (安装的时候有报红)
2. yarn run dev （客户端启动了，但是是项目的目录，而且两个dev-tool工具窗口）

**Comment by hilanmiao** [comment]
> 1. yarn install (安装的时候有报红)
> 2. yarn run dev （客户端启动了，但是是项目的目录，而且两个dev-tool工具窗口）

删除node_modules重新安装，使用npm 安装试试。我刚才用新电脑试了试没有问题。
